name: sglang opensourse sync datasets and models
on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/config/sglang-downloaded-datasets.ini"
      - ".github/workflows/config/sglang-downloaded-models.ini"
      - ".github/workflows/sglang-opensourse-sync-models-datasets.yml"

concurrency:
  group: sync-models-datasets-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync_dataset:
    uses: ./.github/workflows/reusable-sync-models-datasets.yml
    with:
      runs_on: linux-amd64-sglang-guiyang004
      models_config: .github/workflows/config/sglang-downloaded-models.ini
      datasets_config: .github/workflows/config/sglang-downloaded-datasets.ini
